name: Build

on: 
  push:
    branches: [ 88-add-github-automated-build-integration-tests-for-sadb-mariadb-interface ]
  pull_request:

jobs:
  debug_libgcrypt_build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get install -y libgpg-error-dev libgcrypt20-dev libmariadb-dev libmariadb-dev-compat

    - name: Install MariaDB
      run sudo apt-get install -y mariadb-client mariadb-server mariadb-common
    - name: Which MYSQL
      run: which mysql && mysql --version


