name: Build

on: 
  push:
    branches: [ 88-add-github-automated-build-integration-tests-for-sadb-mariadb-interface ]
  pull_request:

jobs:
  debug_libgcrypt_build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update
      run: sudo apt-get update
      
    - name: Install Dependencies
      run: sudo apt-get install -y libgpg-error-dev libgcrypt20-dev libmariadb-dev libmariadb-dev-compat
    - name: Shutdown Ubuntu MySQL
      run: sudo service mysql stop
      
    - name: Setup MariaDB
    - uses: getong/mariadb-action@v1.1
      with: 
        mysql root password: 'itc123!'
        mysql user: 'developer'
        mysql password: 'itc123!'
        
    - name: Which MariaDB
      run: which mysql && mysql --version


